import { OptionType } from "../../sanity";

export const GARFIELD_HOME_MESSAGES = [
  "WHEREEVER UR GOING, UR ALREADY THERE",
  "I KNOW THINGS I SHOULDN'T",
  "TOOK HIM WAY TOO LONG TO MAKE THIS",
  "HE'S GOT IMPOSTER SYNDROME",
  "CAN YOU TURN YOUR WEBCAM ON?",
  "I LIKE THAT ONE BILLIE EILISH SONG",
  "EMAIL HIM, HE'll LOVE IT",
];

const GARFIELD_WEBSITE_MESSAGES = [
  "I KNOW HIS GITHUB PASSWORD",
  "HE HARDCODED ME",
  "ALL HIS CODE IS ON GITHUB",
  "STEAL HIS CODE. IT'S EASY",
  "TOOK HIM WAY TOO LONG TO MAKE THIS",
];

const GARFIELD_FILM_MESSAGES = [
  "HIS YOUTUBE HAS EXTRA CONTENT",
  'LOOK UP "MA BROS TRICK SHOTS"',
  "HIS COLLEGE CHANNEL IS ALMOND FACTORY",
  "HIS YOUTUBE HAS UNLISTED CONTENT",
  "HIS LETTERBOXD IS W3IRDFISH3S",
  "HAVE YOU SEEN THE NEW GARFIELD?",
];

const GARFIELD_DJ_MESSAGES = [
  "HIS FIRST SET EVER? YIKES",
  "HE THINKS HE'S YOUTUBE FAMOUS",
  "I'VE SEEN HIM USE BEAT SYNC",
  "HIS SOUNDCLOUD HAS EXTRA CONTENT",
  "STEAL HIS TRACKS. IT'S EASY",
];

const GARFIELD_MISC_MESSAGES = [
  "THIS SECTION USED TO BE BLOGS",
  "HE TRIED INKTOBER AGAIN BUT GAVE UP",
  "MIS-CEL-LA-NE-OUS",
  "I'VE SEEN THE APPLE MURDERER",
  "APPLE MURDERER IS ACTUALLY A CHILL GUY",
];

export const OPTION_TYPE_TO_GARFIELD_MESSAGES: Record<OptionType, string[]> = {
  website: GARFIELD_WEBSITE_MESSAGES,
  film: GARFIELD_FILM_MESSAGES,
  dj: GARFIELD_DJ_MESSAGES,
  blog: GARFIELD_MISC_MESSAGES,
  about: [],
};
